/* Device-local drawing relay. No external dependencies or requests. */
(() => {
 'use strict';
 const $=s=>document.querySelector(s), app=$('#app'), modal=$('#dialog');
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const clone=x=>JSON.parse(JSON.stringify(x));
 let game=null, completed=null, db=null, view='home', busy=false, ticker=null, lastTick=0, saving=Promise.resolve(), saveError=false;
 let tool={color:'#283831',width:7,erase:false}, redo=[], stroke=null, board=null, ctx=null, setupNames=Array.from({length:12},(_,i)=>'プレイヤー'+(i+1)), setupCount=4, watch=null, expired=false, swRegistration=null;
 const colors=['#283831','#d45c54','#e3af37','#4f8764','#4b7eaa','#9270a8'];
 const current=()=>game?.rounds[game.index];
 const step=()=>current()?.steps[current().cursor];
 const player=()=>game.players[step().player];
 function notify(message){$('#notice').textContent=message;$('#notice').style.display='block';clearTimeout(notify.id);notify.id=setTimeout(()=>$('#notice').style.display='none',4500);}
 function dialog(title,body,buttons){stopTimer();modal.close();$('#dialog-content').innerHTML=`<h2>${esc(title)}</h2><p>${esc(body)}</p><div class="actions">${buttons.map((b,i)=>`<button data-dialog="${i}" class="${b.style||''}">${esc(b.label)}</button>`).join('')}</div>`;modal.showModal();buttons.forEach((b,i)=>$(`[data-dialog="${i}"]`).onclick=async()=>{modal.close();await b.fn();});}
 function request(req){return new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
 async function openDB(){const req=indexedDB.open('drawing-relay',1);req.onupgradeneeded=()=>req.result.createObjectStore('games');req.onblocked=()=>notify('別の画面で開いているゲームを閉じてください。');db=await request(req);db.onversionchange=()=>db.close();}
 function transaction(values){return new Promise((resolve,reject)=>{const tx=db.transaction('games','readwrite');for(const [key,value] of Object.entries(values)){if(value===null)tx.objectStore('games').delete(key);else tx.objectStore('games').put(value,key);}tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('保存中断'));});}
 function enqueue(values){const snapshot=clone(values);const result=saving.catch(()=>{}).then(()=>{if(!db)throw Error('保存が利用できません');return transaction(snapshot);});saving=result;result.then(()=>{saveError=false;},()=>{saveError=true;notify('保存できませんでした。入力は画面内に残っています。もう一度お試しください。');});return result;}
 const saveDraft=()=>game?.status==='playing'?enqueue({active:game}).catch(()=>{}):Promise.resolve();
 async function change(next){await enqueue({active:next});game=next;}
 function safePhase(){return ['reveal','revealWait','finished'].includes(game?.phase)?game.phase:'handoff';}
 function stopTimer(){if(ticker){tick();clearInterval(ticker);ticker=null;}lastTick=0;}
 function tick(){if(!lastTick||!step())return;const now=performance.now();const delta=(now-lastTick)/1000;lastTick=now;const s=step();if(s.remaining>0){s.remaining=Math.max(0,s.remaining-delta);updateTime();if(s.remaining===0){clearInterval(ticker);ticker=null;lastTick=0;timeUp();}}}
 function startTimer(){if(!['draw','guess'].includes(view)||!step()||step().remaining<=0||expired)return;lastTick=performance.now();ticker=setInterval(()=>{tick();saveDraft();},500);}
 function updateTime(){const el=$('#timer');if(!el||!step())return;const unlimited=(step().type==='draw'?game.settings.drawTime:game.settings.guessTime)===0;el.textContent=unlimited?'時間は自由':step().remaining===0?'時間です':`残り ${Math.ceil(step().remaining)} 秒`;el.classList.toggle('warn',!unlimited&&step().remaining<=10);}
 function beep(){if(!game.settings.sound)return;try{const audio=new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=660;g.gain.value=.09;o.start();o.stop(audio.currentTime+.2);o.onended=()=>audio.close();}catch{}}
 function valid(){const s=step();if(s.type==='guess')return Boolean(s.text.trim());if(s.type==='prompt')return true;if(!board)return false;const data=ctx.getImageData(0,0,board.width,board.height).data;for(let i=0;i<data.length;i+=4)if(data[i]<248||data[i+1]<248||data[i+2]<248)return true;return false;}
 function timeUp(){if(!['draw','guess'].includes(view))return;finishStroke();expired=true;beep();dialog('時間です',valid()?'この内容で次の人へ渡しましょう。':'まだ空欄です。ひとつ描くか、思いついた答えを書いてください。',valid()?[{label:'この内容で確定',fn:commit},{label:'内容を確認',style:'secondary',fn:()=>render()}]:[{label:'入力を続ける',fn:()=>{expired=false;step().remaining=0;render();}}]);}
 function detach(){stopTimer();finishStroke();if(watch){watch.disconnect();watch=null;}board=null;ctx=null;}
 function render(){detach();$('#leave').hidden=!game||view==='home'||view==='setup'||view==='rules'||view==='finished';let html='';
   if(view==='home')html=homeHTML();
   if(view==='setup')html=setupHTML();
   if(view==='rules')html=rulesHTML();
   if(view==='handoff')html=handoffHTML();
   if(view==='prompt'||view==='preview')html=promptHTML();
   if(view==='draw')html=drawHTML();
   if(view==='guess')html=guessHTML();
   if(view==='confirm')html=confirmHTML();
   if(view==='revealWait')html=`<section class="center panel handoff"><div class="eyebrow">ROUND ${game.index+1} / ${game.settings.rounds}</div><div class="avatar">✦</div><h1>みんな、集まって！</h1><p class="sub">伝言がつながりました。<br>今度は全員で画面を見てください。</p><button data-action="reveal" class="yellow">答え合わせをする</button></section>`;
   if(view==='reveal')html=revealHTML();
   if(view==='all')html=allHTML();
   if(view==='finished')html=finishedHTML();
   app.innerHTML=html;app.querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>act(el.dataset.action,el.dataset.value));
   if(view==='setup')bindSetup();
   if(view==='draw')bindBoard();
   if(view==='guess'){const input=$('#answer');input.addEventListener('input',()=>{step().text=input.value;clearTimeout(input.save);input.save=setTimeout(saveDraft,180);});}
   if(['draw','guess'].includes(view)){updateTime();startTimer();}
 }
 const catSVG=`<svg class="sketch-cat" viewBox="0 0 200 145" fill="none" stroke="#35654e" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M53 72 49 21 80 40Q100 29 121 40L151 21 146 76Q156 119 101 127Q46 121 53 72Z"/><path d="M71 73h4m48 0h4m-32 17 6 5 6-5m-6 5v9m0-1q-14 13-21 0m21 0q14 13 21 0M41 89l-23-6m22 18-24 5m142-17 23-6m-23 18 24 5"/></svg>`;
 function homeHTML(){return `<section class="hero"><div><div class="eyebrow">DRAW · PASS · GUESS</div><h1>絵でつないで、<br><span>みんなで笑おう。</span></h1><p class="sub">言葉が絵になって、絵が言葉になる。<br>タブレットを回すたび、伝言は思わぬ方向へ。</p><div class="actions"><button data-action="setup" class="yellow">ゲームをはじめる →</button>${game?'<button data-action="resume">つづきから</button>':''}<button class="secondary" data-action="how">遊び方</button></div><div class="pills"><span class="pill">3〜12人</span><span class="pill">タブレット1台</span><span class="pill">絵が苦手でもOK</span></div></div><div class="art" aria-hidden="true"><div class="paper-card"><div class="label">01 / 最初のお題</div><div class="word">ねこ</div><div class="label">この言葉を、絵にしてみよう。</div></div><div class="arrow">↷</div><div class="paper-card second"><div class="label">02 / 描いてつなぐ</div>${catSVG}<div class="label">次の人には、絵だけ見せて。</div></div></div></section><section class="intro-grid"><article class="intro"><span class="number">1</span><h3>こっそり描く</h3><p>お題を見て、指やペンでお絵描き。<br>文字や数字は使わずに。</p></article><article class="intro"><span class="number">2</span><h3>渡して、当てる</h3><p>絵を見て、何かを言葉で答える。<br>その言葉を次の人がまた描く。</p></article><article class="intro"><span class="number">3</span><h3>一緒に答え合わせ</h3><p>最初と最後は、どう変わった？<br>みんなの伝言を順に見てみよう。</p></article></section><div class="actions">${completed?'<button class="secondary small" data-action="old">前のゲームの結果</button>':''}<button class="secondary small" data-action="delete">保存データを削除</button></div><p class="offline" id="offline-status">${location.protocol==='file:'?'このファイルはネット接続なしで遊べます。保存はこのブラウザ内のみです。':'オフライン利用を準備しています…'}</p>`;}
 function options(values,selected){return values.map(([v,t])=>`<option value="${v}" ${String(v)===String(selected)?'selected':''}>${esc(t)}</option>`).join('');}
 function setupHTML(){return `<div class="heading"><div><div class="eyebrow">LET'S GET READY</div><h1>みんなで遊ぶ準備</h1><p>座っている順に名前を入れよう。端末もこの順に回します。</p></div><button class="secondary" data-action="home">ホームへ</button></div><div class="setup-grid"><section class="panel"><h2>参加メンバー</h2><label class="field"><span>人数</span><select id="count">${options(Array.from({length:10},(_,i)=>[i+3,(i+3)+'人'+(i+3===3?'（体験用）':'')]),setupCount)}</select></label><div class="names" id="names">${namesHTML()}</div><p class="help" id="odd-help">${setupCount%2?'奇数人数では最初の人がお題係です。このラウンドは描かず、次のラウンドで交代します。':'全員が1回ずつ、描くか推測します。'}</p></section><section class="panel"><h2>遊び方の設定</h2><label class="field"><span>お題のカテゴリ</span><select id="category">${options(['すべて',...Object.keys(TeleCore.groups)].map(x=>[x,x]),'すべて')}</select></label><label class="field"><span>ラウンド数</span><select id="rounds">${options([[1,'1ラウンド · お試し'],[3,'3ラウンド · おすすめ'],[5,'5ラウンド'],['all','人数分 · 全員が先頭に']],3)}</select></label><label class="field"><span>描く時間</span><select id="draw-time">${options([[30,'30秒'],[60,'60秒'],[90,'90秒'],[0,'無制限']],60)}</select></label><label class="field"><span>推測する時間</span><select id="guess-time">${options([[30,'30秒'],[60,'60秒'],[0,'無制限']],30)}</select></label><label class="check"><input type="checkbox" id="sound"><span>時間切れの音を鳴らす</span></label><p class="help">点数はつけません。伝わり方を楽しもう。</p><button class="yellow" data-action="create" style="width:100%">このメンバーで遊ぶ →</button></section></div>`;}
 function namesHTML(){return setupNames.slice(0,setupCount).map((name,i)=>`<label class="name-row"><b>${i+1}</b><input data-name="${i}" aria-label="${i+1}人目の名前" maxlength="20" value="${esc(name)}"></label>`).join('');}
 function bindSetup(){const bindNames=()=>app.querySelectorAll('[data-name]').forEach(input=>input.oninput=()=>setupNames[Number(input.dataset.name)]=input.value);bindNames();$('#count').onchange=e=>{setupCount=Number(e.target.value);$('#names').innerHTML=namesHTML();$('#odd-help').textContent=setupCount%2?'奇数人数では最初の人がお題係です。このラウンドは描かず、次のラウンドで交代します。':'全員が1回ずつ、描くか推測します。';bindNames();};}
 function rulesHTML(){return `<section class="center panel"><div class="eyebrow">HOW TO PLAY</div><h1>最初に、約束を3つ。</h1><ol class="rule-list"><li>ほかの人に画面を見せない。相談しない。</li><li>絵には文字・数字を書かない。</li><li>分からなくても、思いついた答えを書く。</li></ol><p class="help">1本の伝言をみんなで回し、最後にまとめて公開します。<br>${game.players.length%2?'今回は奇数人数。最初の人はお題係になり、次の人が描きます。':'最初の人がお題を見て描きます。'}<br>次のラウンドでは、先頭が1人ずれます。</p><p>最初は <strong>${esc(game.players[0])}</strong> さんから。</p><button class="yellow" data-action="ready">わかった、はじめよう →</button></section>`;}
 function progressHTML(){return `<div class="progress" aria-label="${current().cursor+1} / ${current().steps.length}人目">${current().steps.map((s,i)=>`<i class="${i<current().cursor?'done':''}"></i>`).join('')}</div>`;}
 function handoffHTML(){return `<section class="center panel handoff"><div class="eyebrow">ROUND ${game.index+1} / ${game.settings.rounds}</div><span class="badge">${current().cursor+1} / ${game.players.length}人目</span><div class="avatar">↪</div><div class="player">${esc(player())} さん</div><h2 style="margin-top:12px">に渡してください</h2><p class="sub">受け取ったら、周りに見えないように。<br>自分の名前を確認してから始めよう。</p><button class="yellow" data-action="begin">私は${esc(player())}です・始める</button>${progressHTML()}<p class="help">画面の中身は、まだ隠れています。</p></section>`;}
 function referenceText(){const r=current(),i=r.cursor;return i===0||r.steps[i-1].type==='prompt'?r.prompt.text:r.steps[i-1].text;}
 function promptHTML(){return `<section class="center panel handoff"><div class="eyebrow">${view==='prompt'?'あなたは、お題係':'最初のお題を確認'}</div><h1>${view==='prompt'?'お題をこっそり見てね':'この言葉を描こう'}</h1><div class="result-word">${esc(current().prompt.text)}</div><p class="help">${view==='prompt'?'このラウンドでは描きません。確認したら、画面を隠して次の人へ。':'「描きはじめる」を押すと時間がスタートします。'}</p><div class="actions" style="justify-content:center">${current().cursor===0?'<button class="secondary" data-action="reroll">別のお題にする</button>':''}<button class="yellow" data-action="${view==='prompt'?'promptDone':'startDraw'}">${view==='prompt'?'確認して、隠す →':'描きはじめる →'}</button></div><div class="actions" style="justify-content:center"><button class="secondary small" data-action="hide">すぐ隠す</button></div></section>`;}
 function playTop(title,help){return `<div class="play-top"><div><div class="eyebrow">ROUND ${game.index+1} · ${esc(player())} さん</div><h1>${title}</h1><p class="help">${help}</p></div><div class="timer" id="timer"></div></div>`;}
 function drawHTML(){return `${playTop('言葉を、絵にしよう。','文字・数字は使わずに。うまく描けなくても大丈夫。')}<div class="reference"><small>描く言葉</small><strong>${esc(referenceText())}</strong></div><div class="canvas-wrap"><canvas class="board" id="board" width="1000" height="600" aria-label="お絵描き用キャンバス"></canvas></div><div class="tools" role="group" aria-label="描画道具">${colors.map((c,i)=>`<button class="swatch ${!tool.erase&&tool.color===c?'selected':''}" data-action="color" data-value="${c}" aria-label="${['黒','赤','黄','緑','青','紫'][i]}のペン" aria-pressed="${!tool.erase&&tool.color===c}"><span style="background:${c}"></span></button>`).join('')}<button class="secondary ${tool.erase?'selected':''}" data-action="eraser" aria-pressed="${tool.erase}">消しゴム</button>${[3,7,14].map((w,i)=>`<button class="secondary ${tool.width===w?'selected':''}" data-action="width" data-value="${w}" aria-pressed="${tool.width===w}">${['細','中','太'][i]}</button>`).join('')}<span class="spacer"></span><button class="secondary" data-action="undo" aria-label="1操作戻す">↶</button><button class="secondary" data-action="redo" aria-label="やり直す">↷</button><button class="secondary" data-action="clear">全消去</button></div><div class="play-actions"><button class="secondary" data-action="hide">すぐ隠す</button><button class="yellow primary" data-action="done">できた →</button></div>`;}
 function guessHTML(){const previous=current().steps[current().cursor-1];return `${playTop('これは、何の絵？','分からなくても、思いついた答えを書こう。')}<div class="guess-layout"><img src="${previous.image}" alt="直前の人が描いた絵"><section class="panel guess-input"><label class="field"><span>絵を見て、言葉で答える</span><input id="answer" autocomplete="off" maxlength="50" placeholder="何に見える？" value="${esc(step().text)}" ${expired?'disabled':''}></label><p class="help">正解より、あなたに見えたものを。<br>次の人は、この言葉を絵にします。</p><button class="yellow" data-action="done">できた →</button><button class="secondary" data-action="hide">すぐ隠す</button></section></div>`;}
 function confirmHTML(){return `<section class="center panel handoff"><div class="eyebrow">READY TO PASS?</div><div class="avatar">✓</div><h1>この内容で渡しますか？</h1><p class="sub">確定すると、内容を隠します。<br>あとから書き直すことはできません。</p><div class="actions" style="justify-content:center"><button class="secondary" data-action="edit">修正する</button><button class="yellow" data-action="commit">確定して、隠す →</button></div><button class="secondary small" data-action="hide">すぐ隠す</button></section>`;}
 function revealHTML(){const r=current(),i=r.reveal,s=i? r.steps.filter(x=>x.type!=='prompt')[i-1]:null,total=r.steps.filter(x=>x.type!=='prompt').length;return `<div class="heading"><div><div class="eyebrow">THE BIG REVEAL · ROUND ${game.index+1}</div><h1>伝言、どう変わった？</h1><p>ひとつずつ見ていこう。</p></div><span class="badge">${i+1} / ${total+1}ページ</span></div><section class="panel result-card"><div class="eyebrow">${i===0?'最初のお題':`${esc(game.players[s.player])} さんの${s.type==='draw'?'絵':'推測'}`}</div>${s?.type==='draw'?`<img class="result-image" src="${s.image}" alt="${esc(game.players[s.player])}さんが描いた絵">`:`<div class="result-word">${esc(s?s.text:r.prompt.text)}</div>`}<div class="dots">${Array.from({length:total+1},(_,j)=>`<i class="${j===i?'on':''}"></i>`).join('')}</div><div class="result-nav"><button class="secondary" data-action="prev" ${i===0?'disabled':''}>← 前へ</button><button class="yellow" data-action="${i===total?'all':'next'}">${i===total?'全体を見る →':'次を見せる →'}</button></div></section>`;}
 function allHTML(){const r=current(),steps=r.steps.filter(s=>s.type!=='prompt');return `<div class="heading"><div><div class="eyebrow">ROUND ${game.index+1} · RECAP</div><h1>こんな伝言になりました。</h1></div><button class="secondary" data-action="replay">もう一度、順に見る</button></div><div class="comparison"><div><small>最初のお題</small><br><strong>${esc(r.prompt.text)}</strong></div><span>→</span><div><small>最後の言葉</small><br><strong>${esc(steps.at(-1).text)}</strong></div></div><div class="timeline"><article class="panel"><small>01 · お題</small><p>${esc(r.prompt.text)}</p></article>${steps.map((s,i)=>`<article class="panel"><small>${String(i+2).padStart(2,'0')} · ${esc(game.players[s.player])} さん</small>${s.type==='draw'?`<img src="${s.image}" alt="${esc(game.players[s.player])}さんの絵">`:`<p>${esc(s.text)}</p>`}</article>`).join('')}</div><div class="actions" style="justify-content:center"><button class="yellow" data-action="${game.status==='completed'?'finished':game.index+1<game.settings.rounds?'nextRound':'finish'}">${game.status==='completed'?'結果一覧へ':game.index+1<game.settings.rounds?'次のラウンドへ →':'ゲームを終える →'}</button></div>`;}
 function finishedHTML(){return `<section class="center panel"><div class="eyebrow">THANKS FOR PLAYING</div><div class="avatar">✦</div><h1>みんなの伝言、完成！</h1><p class="sub">同じ言葉でも、見え方はいろいろ。<br>また一緒に遊ぼう。</p><div class="actions" style="justify-content:center"><button class="yellow" data-action="again">同じメンバーでもう一度</button><button class="secondary" data-action="home">ホームへ</button></div></section><div class="timeline">${game.rounds.map((r,i)=>`<button class="panel secondary" data-action="review" data-value="${i}" style="text-align:left"><div class="eyebrow">ROUND ${i+1}</div><strong>${esc(r.prompt.text)}</strong><p style="font-size:16px;margin-bottom:0">→ ${esc(r.steps.at(-1).text)}</p></button>`).join('')}</div>`;}
 function paint(strokes,canvas){const c=canvas.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,1000,600);for(const s of strokes){if(!s.points.length)continue;c.strokeStyle=s.erase?'#fff':s.color;c.fillStyle=c.strokeStyle;c.lineWidth=s.erase?s.width*3:s.width;c.lineCap='round';c.lineJoin='round';c.beginPath();c.moveTo(...s.points[0]);if(s.points.length===1){c.arc(s.points[0][0],s.points[0][1],c.lineWidth/2,0,Math.PI*2);c.fill();}else{for(const p of s.points.slice(1))c.lineTo(...p);c.stroke();}}}
 function repaint(){if(board)paint(step().strokes,board);}
 function finishStroke(){if(!stroke)return;step().strokes.push(stroke);stroke=null;redo=[];repaint();saveDraft();}
 function bindBoard(){board=$('#board');ctx=board.getContext('2d',{willReadFrequently:true});repaint();const position=e=>{const r=board.getBoundingClientRect();return [Math.max(0,Math.min(1000,(e.clientX-r.left)/r.width*1000)),Math.max(0,Math.min(600,(e.clientY-r.top)/r.height*600))];};let activePointer=null;
   board.onpointerdown=e=>{if(expired||stroke||e.button>0)return;e.preventDefault();activePointer=e.pointerId;board.setPointerCapture(e.pointerId);stroke={color:tool.color,width:tool.width,erase:tool.erase,points:[position(e)]};paint([...step().strokes,stroke],board);};
   board.onpointermove=e=>{if(!stroke||e.pointerId!==activePointer)return;e.preventDefault();for(const event of e.getCoalescedEvents?.()||[e])stroke.points.push(position(event));paint([...step().strokes,stroke],board);};
   board.onpointerup=board.onpointercancel=board.onlostpointercapture=e=>{if(e.pointerId===activePointer){finishStroke();activePointer=null;}};
   watch=new ResizeObserver(()=>repaint());watch.observe(board);
 }
 function drawingImage(s){const c=document.createElement('canvas');c.width=1000;c.height=600;paint(s.strokes,c);return c.toDataURL('image/png');}
 async function commit(){if(busy)return;busy=true;stopTimer();finishStroke();try{const next=clone(game),r=next.rounds[next.index],s=r.steps[r.cursor];if(s.done)return;if(s.type==='draw')s.image=drawingImage(s);if(s.type==='guess'){s.text=s.text.trim();if(!s.text)throw Error('答えを書いてください');}s.done=true;r.cursor++;next.phase=r.cursor===r.steps.length?'revealWait':'handoff';await change(next);expired=false;redo=[];view=game.phase;render();window.scrollTo(0,0);}catch{notify('保存できませんでした。内容を保持しています。確定をもう一度押してください。');}finally{busy=false;}}
 function hide(){if(!game||!['draw','guess','prompt','preview','confirm'].includes(view))return;stopTimer();finishStroke();game.phase='handoff';view='handoff';saveDraft();modal.close();render();}
 async function act(action,value){if(busy)return;
   switch(action){
   case 'home': stopTimer();if(game?.status==='completed')game=null;view='home';render();updateOffline();safeUpdate();break;
   case 'setup': if(game?.status==='playing'){dialog('新しくはじめますか？','進行中のゲームを置き換えます。',[{label:'つづきを遊ぶ',fn:()=>act('resume')},{label:'新しくはじめる',style:'danger',fn:()=>{view='setup';render();}}]);}else{view='setup';render();}break;
   case 'resume':view=safePhase();expired=false;render();break;
   case 'how':dialog('遊び方','言葉を絵にし、次の人が絵を言葉で推測。その言葉をまた絵にします。最後に全員で公開します。文字・数字で描かず、途中は相談しません。3人は短い体験用、4〜8人がおすすめ。奇数人数では先頭がお題係になり、次のラウンドで交代します。',[{label:'わかった',fn:()=>{}}]);break;
   case 'create':{const players=setupNames.slice(0,setupCount).map((n,i)=>n.trim()||'プレイヤー'+(i+1));const settings={category:$('#category').value,rounds:$('#rounds').value==='all'?setupCount:Number($('#rounds').value),drawTime:Number($('#draw-time').value),guessTime:Number($('#guess-time').value),sound:$('#sound').checked};const next=TeleCore.create(players,settings);const create=async()=>{busy=true;try{await enqueue({active:next,completed:null});game=next;completed=null;view='rules';render();}catch{notify('保存を利用できません。ブラウザの保存設定をご確認ください。');}finally{busy=false;}};if(completed)dialog('新しいゲームをはじめます','前のゲームの結果は置き換えられます。',[{label:'戻る',style:'secondary',fn:()=>{}},{label:'はじめる',fn:create}]);else await create();break;}
   case 'ready':game.phase='handoff';await saveDraft();view='handoff';render();break;
   case 'begin':{const s=step();expired=false;if(s.type==='prompt')view='prompt';else if(s.type==='draw'&&!s.started&&(current().cursor===0||current().steps[current().cursor-1].type==='prompt'))view='preview';else {view=s.type;s.started=true;}game.phase=view;await saveDraft();render();if(step().started&&step().remaining===0&&(step().type==='draw'?game.settings.drawTime:game.settings.guessTime)>0)timeUp();break;}
   case 'startDraw':step().started=true;game.phase='draw';view='draw';await saveDraft();render();break;
   case 'reroll':{if(current().cursor!==0||step().started)return;const p=TeleCore.choose(game.settings.category,game.used);if(!p){notify('このカテゴリのお題をすべて使いました。次の抽選から再使用します。');game.used=[];return;}const next=clone(game);next.used.push(p.id);next.rounds[next.index].prompt=p;busy=true;try{await change(next);render();}catch{}finally{busy=false;}break;}
   case 'promptDone':await commit();break;
   case 'hide':hide();break;
   case 'color':tool.color=value;tool.erase=false;refreshTools();break;
   case 'eraser':tool.erase=!tool.erase;refreshTools();break;
   case 'width':tool.width=Number(value);refreshTools();break;
   case 'undo':if(expired)break;finishStroke();if(step().strokes.length)redo.push(step().strokes.pop());repaint();saveDraft();break;
   case 'redo':if(expired)break;if(redo.length)step().strokes.push(redo.pop());repaint();saveDraft();break;
   case 'clear':if(expired)break;dialog('絵を全部消しますか？','いま描いている絵が白紙になります。',[{label:'戻る',style:'secondary',fn:()=>startTimer()},{label:'全部消す',style:'danger',fn:()=>{step().strokes=[];redo=[];repaint();saveDraft();startTimer();}}]);break;
   case 'done':stopTimer();finishStroke();if(!valid()){notify(step().type==='draw'?'ひとつ描いてから渡そう。':'思いついた答えを書いてね。');startTimer();return;}view='confirm';game.phase='confirm';saveDraft();render();break;
   case 'edit':view=step().type;game.phase=view;render();break;
   case 'commit':await commit();break;
   case 'reveal':game.phase='reveal';current().reveal=0;await saveDraft();view='reveal';render();break;
   case 'next':current().reveal=Math.min(current().reveal+1,current().steps.filter(s=>s.type!=='prompt').length);await saveDraft();render();break;
   case 'prev':current().reveal=Math.max(0,current().reveal-1);saveDraft();render();break;
   case 'all':view='all';render();window.scrollTo(0,0);break;
   case 'replay':current().reveal=0;view='reveal';render();break;
   case 'nextRound':{busy=true;try{const next=clone(game);next.index++;next.rounds.push(TeleCore.round(next,next.index));next.phase='handoff';await change(next);view='handoff';render();window.scrollTo(0,0);}catch{notify('次のラウンドを保存できませんでした。もう一度お試しください。');}finally{busy=false;}break;}
   case 'finish':{busy=true;try{const next=clone(game);next.status='completed';next.phase='finished';await enqueue({active:null,completed:next});game=next;completed=clone(next);view='finished';render();safeUpdate();}catch{}finally{busy=false;}break;}
   case 'finished':view='finished';render();break;
   case 'review':game.index=Number(value);view='all';render();window.scrollTo(0,0);break;
   case 'old':game=clone(completed);view='finished';render();break;
   case 'again':setupNames=[...game.players,...setupNames.slice(game.players.length)];setupCount=game.players.length;game=null;view='setup';render();break;
   case 'delete':dialog('保存データを削除しますか？','進行中のゲームと前の結果を、このブラウザから削除します。',[{label:'戻る',style:'secondary',fn:()=>{}},{label:'削除する',style:'danger',fn:async()=>{try{await enqueue({active:null,completed:null});game=null;completed=null;view='home';render();updateOffline();notify('保存データを削除しました。');}catch{}}}]);break;
   }
 }
 function refreshTools(){app.querySelectorAll('.swatch').forEach(b=>{const selected=!tool.erase&&b.dataset.value===tool.color;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',selected);});const eraser=$('[data-action="eraser"]');eraser.classList.toggle('selected',tool.erase);eraser.setAttribute('aria-pressed',tool.erase);app.querySelectorAll('[data-action="width"]').forEach(b=>{b.classList.toggle('selected',Number(b.dataset.value)===tool.width);b.setAttribute('aria-pressed',Number(b.dataset.value)===tool.width);});}
 function leave(){if(!game||game.status!=='playing'){act('home');return;}hide();stopTimer();dialog('ひと休みしますか？','ゲームはこのブラウザに保存されます。再開時は内容を隠した画面から始まります。',[{label:'ゲームに戻る',style:'secondary',fn:()=>render()},{label:'保存してホームへ',fn:async()=>{await saving.catch(()=>{});if(saveError){notify('保存できていません。ゲームを閉じずに再試行してください。');await saveDraft();if(saveError)return;}view='home';render();updateOffline();}},{label:'ゲームを破棄',style:'danger',fn:()=>dialog('ゲームを破棄しますか？','このゲームの絵と回答を削除します。',[{label:'戻る',style:'secondary',fn:()=>render()},{label:'破棄する',style:'danger',fn:async()=>{try{await enqueue({active:null});game=null;view='home';render();updateOffline();safeUpdate();}catch{}}}])}]);}
 $('#leave').onclick=leave;$('#brand').onclick=e=>{e.preventDefault();if(game?.status==='playing'&&!['home','setup'].includes(view))leave();else act('home');};
 document.addEventListener('visibilitychange',()=>{if(document.hidden)hide();});window.addEventListener('pagehide',()=>{hide();saveDraft();});window.addEventListener('popstate',()=>{hide();if(game?.status==='playing')leave();});modal.addEventListener('cancel',e=>{e.preventDefault();modal.close();if(expired){view='handoff';game.phase='handoff';saveDraft();render();}else startTimer();});
 async function updateOffline(){const el=$('#offline-status');if(!el||location.protocol==='file:')return;try{const cached=await caches.match(new URL('app.js',location.href));el.textContent=cached?'オフライン準備完了 · この端末だけに保存します。':'初回読み込み後、オフラインで遊べます。';}catch{el.textContent='保存はこのブラウザ内のみです。';}}
 function safeUpdate(){if((!game||game.status==='completed')&&swRegistration?.waiting)swRegistration.waiting.postMessage('UPDATE_SAFE');}
 async function init(){app.innerHTML='<p class="loading">お絵描きの準備中…</p>';try{await openDB();const tx=db.transaction('games','readonly');[game,completed]=await Promise.all([request(tx.objectStore('games').get('active')),request(tx.objectStore('games').get('completed'))]);game=game||null;completed=completed||null;if(game?.schemaVersion!==1)game=null;if(game){game.phase=safePhase();await saveDraft();}}catch{notify('保存機能を利用できません。通常のブラウザで開いてください。');}render();if('serviceWorker'in navigator&&location.protocol!=='file:'){try{swRegistration=await navigator.serviceWorker.register('sw.js');await navigator.serviceWorker.ready;updateOffline();swRegistration.addEventListener('updatefound',()=>{const worker=swRegistration.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'){updateOffline();safeUpdate();}});});safeUpdate();}catch{notify('オフライン準備ができませんでした。ネット接続中は遊べます。');}}updateOffline();}
 init();
})();
